### ISSUE TITLE
License

### ISSUE THREAD

**Issue by robputt796** [rheh/HTML5-canvas-projects#3]
Hi Ray,

Please can you let me know which license applies to the code in this repo, I would like to utilise some of the JS you have written, but would like to check it is open and of a license in which I may do so.

Best Regards,

Rob

**Comment by rheh** [comment]
Hi Rob,

The code is open and free to use.  No credit necessary.  Good luck with
your project.

Thanks

Rah

**Comment by robputt796** [comment]
Thanks Ray!

Closing issue.
